@startuml
'https://plantuml.com/class-diagram

namespace Repository {
    abstract class Repository {
        + CreateStorage(byte[] data);
        + GetStorages();
    }

    class RepositoryLocal {
        + DirectoryInfo dirInfo
    }

    class RepositoryRemote {
        + string Address
        + int Port
    }

    Repository <-- RepositoryLocal
    Repository <-- RepositoryRemote
}
class BackupJob {
    + Repository
    + StorageType
    + HashSet<JobObject> files
    + List<RestorePoint> restorePoints

    + Add(JobObject)
    + Remove(JobObject)
    + CreateRestorePoint()
}

class JobObject {
    + string FileName
    + string RootPath
    + byte[] GetData()
}

enum StorageType{
    SplitStorages
    SingleStorage
}

class RestorePoint {
    + long CreationDateUtc
    + List<string> StorageIds
}

BackupJob -down-|> StorageType
BackupJob -down-|> JobObject : GetData()
BackupJob <|-down-- JobObject : byte[]
BackupJob -down-|> RestorePoint : StorageIds
BackupJob <|-down- RestorePoint : RestorePoint
BackupJob --down-|> Repository : byte[]
BackupJob <|-down-- Repository : storage id

@enduml